version: "3"

services:
  pg:
    image: postgres:15-alpine
    ports:
      - 5432:5432
    container_name: medi_track_pg
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=medi_track
