### profile
GET http://localhost:8080/profile/appointments

### GET ALL
GET http://localhost:8080/appointments

### GET
GET http://localhost:8080/appointments/2

### GET


### POST
POST http://localhost:8080/appointments
Content-Type: application/json

{
  "diagnosis": "lol",
  "timestamp": "2023-12-15T03:03:02",
  "patient": "http://localhost:8080/patients/202",
  "staff": "http://localhost:8080/staff/152"
}

### PATCH
PATCH http://localhost:8080/appointments/1
Content-Type: application/json

{
  "patient": "http://localhost:8080/patients/2",
  "staff": "http://localhost:8080/staff/2"
}